import type { Metadata } from "next";
import { libreBaskerville, rowdies } from "@/components/ui/fonts";
import "./globals.css";
import Header from "@/components/ui/header/Header";
import Footer from "@/components/ui/footer/Footer";

export const metadata: Metadata = {
  title: "PathPicsTales",
  description: "Generated by humans",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${rowdies.className}  antialiased bg-gradient-to-r from-lime-200 via-white to-lime-200 `}>
        <Header />
          <main className="min-h-screen mb-10">
          {children}
        </main>
        <Footer />
      </body>
     
   
     
    </html>
  );
}
